apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chains-hoy-polysensus-io
spec:
  commonName: "chains.hoy.polysensus.io"
  secretName: chains-hoy-polysensus-io
  dnsNames:
    - "chains.hoy.polysensus.io"
    - "*.chains.hoy.polysensus.io"
  issuerRef:
    name: letsencrypt-prod-primary-dns
    kind: ClusterIssuer
