---
version: '3'

tasks:
  caimst-new:
    desc: create (or recreate) the caimst chain. if re-creating this will RE-GENSIS and ROLL SECRETS
    summarry: |
      create/recreate the manifests and any terraform for the caimst chain

      This WILL CAUSE RE-GENSIS and ROLL SECRETS
    cmds:
      - tusk -q new -f caimst

