---
version: '3'

tasks:
  caimst-new:
    desc: create (or recreate) the caimst chain configuration
    summarry: |
      create/recreate the manifests and any terraform for the caimst chain
    cmds:
      - tusk -q new -f caimst

  caimst-genesis:
    desc: Gensis and key generation for caimst
    cmds:
      - tusk -q genesis caimst

  caimst-fluxseal:
    desc: seal or reseal the node secrets
    cmds:
      - tusk -q fluxseal caimst

  caimst:
    cmds:
      - task: caimst-new
      - task: caimst-genesis
      - task: caimst-fluxseal



