apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ethnodetokenexchange
spec:
  forwardAuth:
    # address: http://authex.rrr9.svc.cluster.local:8401/node/exchange
    address: hoy-iam.svc.cluster.local:8401/chains/caimst-209301/node/exchange
    authRequestHeaders:
      - "Accept"
      - "Content-Length"
      - "Content-Type"
      - "User-Agent"
      - "Authorization"
    authResponseHeaders:
      - Authorization
    trustForwardHeader: true
